/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  sepolia: {
    NftFactory: {
      address:
        "0x2cbede71bf5b39ec66b32aadb57610afb14d373ca8ab7328fce700fb255a39d",
      abi: [
        {
          type: "impl",
          name: "NftFactoryImpl",
          interface_name: "contracts::NftFactory::INftFactory",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::NftFactory::INftFactory",
          items: [
            {
              type: "function",
              name: "deploy_nft_contract",
              inputs: [
                {
                  name: "contract_name",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "symbol",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_nft_class_hash",
              inputs: [
                {
                  name: "new_class_hash",
                  type: "core::starknet::class_hash::ClassHash",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_nft_class_hash",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::class_hash::ClassHash",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_deployed_nfts_by_deployer",
              inputs: [
                {
                  name: "deployer",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "OwnableImpl",
          interface_name: "openzeppelin_access::ownable::interface::IOwnable",
        },
        {
          type: "interface",
          name: "openzeppelin_access::ownable::interface::IOwnable",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounce_ownership",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "nft_class_hash",
              type: "core::starknet::class_hash::ClassHash",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::NftFactory::NftFactory::NftClassHashChange",
          kind: "struct",
          members: [
            {
              name: "old_nft_classhash",
              type: "core::starknet::class_hash::ClassHash",
              kind: "key",
            },
            {
              name: "new_nft_classhash",
              type: "core::starknet::class_hash::ClassHash",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::NftFactory::NftFactory::NftContractDeployed",
          kind: "struct",
          members: [
            {
              name: "nft_classhash",
              type: "core::starknet::class_hash::ClassHash",
              kind: "key",
            },
            {
              name: "contract_address",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "deployer_address",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::NftFactory::NftFactory::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
            {
              name: "NftClassHashChange",
              type: "contracts::NftFactory::NftFactory::NftClassHashChange",
              kind: "nested",
            },
            {
              name: "NftContractDeployed",
              type: "contracts::NftFactory::NftFactory::NftContractDeployed",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x2dee73a6cc27a867dc4c2f00bf76078ea2d36716947dff9d42258b85acdd659",
    },
  },
} as const;

export default deployedContracts;
